const mongoose = require('mongoose');

const courseSchema = new mongoose.Schema(
  {
    uniqueId: { type: String, required: true, unique: true, index: true },
    courseName: { type: String, required: true, index: 'text' },
    courseCode: String,
    universityCode: { type: String, index: true },
    universityName: { type: String, index: true },
    departmentSchool: String,
    disciplineMajor: { type: String, index: true },
    specialization: String,
    courseLevel: { type: String, index: true },
    overviewDescription: { type: String, index: 'text' },
    summary: String,
    prerequisites: [String],
    learningOutcomes: [String],
    teachingMethodology: String,
    assessmentMethods: [String],
    credits: Number,
    durationMonths: Number,
    languageOfInstruction: String,
    syllabusUrl: String,
    keywords: [String],
    professorName: String,
    professorEmail: String,
    officeLocation: String,
    openForIntake: String,
    admissionOpenYears: String,
    attendanceType: String,
    firstYearTuitionFee: Number,
    totalTuitionFee: Number,
    tuitionFeeCurrency: String,
    applicationFeeAmount: Number,
    applicationFeeCurrency: String,
    applicationFeeWaived: Boolean,
    requiredApplicationMaterials: String,
    twelfthGradeRequirement: String,
    undergraduateDegreeRequirement: String,
    minimumIELTSScore: Number,
    minimumTOEFLScore: Number,
    minimumPTEScore: Number,
    minimumDuolingoScore: Number,
    minimumCambridgeEnglishScore: String,
    otherEnglishTestsAccepted: String,
    greRequired: Boolean,
    greScore: String,
    gmatRequired: Boolean,
    gmatScore: String,
    satRequired: Boolean,
    satScore: String,
    actRequired: Boolean,
    actScore: String,
    waiverOptions: String,
    partnerCourse: Boolean,
    ftRanking2024: Number,
    acceptanceRate: Number,
    domesticApplicationDeadline: String,
    internationalApplicationDeadline: String,
    courseUrl: String,
  },
  { timestamps: true }
);

courseSchema.index({
  courseName: 'text',
  overviewDescription: 'text',
  summary: 'text',
  disciplineMajor: 'text',
  keywords: 'text',
});

module.exports = mongoose.model('Course', courseSchema);
